.\" Macros
.ds PX \s-1POSIX\s+1
.de EXAMPLE .\" Format de los ejemplos
.RS 10
.BR "\\$1"
.RE
..

.TH socks5dctl 0.0.0 "17 de junio 2022"
.LO 8
.SH NAME
socks5dclt \- cliente del protocolo para el monitoreo del proxy SOCKS version 5 con esteroides

.SH SINOPSIS
.HP 10
.B  socks5dctl [ POSIX style options ]

.SH OPCIONES

.IP "\fB\-L\fB \fIdirección-de-management\fR"
  Establece la dirección donde sirve el servicio de
  management. Por defecto usa localhost.

.IP "\fB\-P\fB \fIpuerto-conf\fR"
  Puerto SCTP  donde escucha el protocolo
  de configuración. Por defecto el valor es \fI8080\fR.

.IP "\fB-h\fR"
  Imprime la ayuda y termina.
